### ISSUE TITLE
Error: Cannot find module 'chalk-pipe'

### ISSUE THREAD

**Issue by hemendpatel** [LitoMore/ink-color-pipe#2]
I'm trying to add color using this library. I'm getting below error.
Anybody getting this issue? 
Step to reproduce:
1. Clone the repository
2. npm i
4. add "module": "CommonJS" in  tsconfig 
3. npm run demo

ink-color-pipe-main\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'chalk-pipe'
Require stack:
- ink-color-pipe-main\dist\source\index.js
- ink-color-pipe-main\dist\example\index.js

**Comment by LitoMore** [comment]
We moved to [ESM](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77). For CommonJS, please use [ink-color-pipe@2.0.0](https://github.com/LitoMore/ink-color-pipe/releases).

**Comment by hemendpatel** [comment]
Thank you @LitoMore. its working with ink-color-pipe@2.0.0.
